Update backup.yml

diff --git a/.github/workflows/backup.yml b/.github/workflows/backup.yml
--- a/.github/workflows/backup.yml
+++ b/.github/workflows/backup.yml
@@ -28,21 +28,21 @@ jobs:
           TIMESTAMP=$(date +"%Y%m%d%H%M%S")
           BRANCH_NAME="backup-$TIMESTAMP"
           echo "Branch name: $BRANCH_NAME"
-          git checkout -b $BRANCH_NAME
+          git checkout -b $BRANCH_NAME || { echo "Branch creation failed"; exit 1; }
           echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
 
       - name: Add backup remote
         run: |
           echo "Adding remote backup repository"
-          git remote add backup https://${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}@github.com/kn-oz/BACKUPREPO.git
+          git remote add backup https://${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}@github.com/kn-oz/BACKUPREPO.git || { echo "Adding remote failed"; exit 1; }
           git remote -v # List remotes to verify
 
       - name: Pull changes from backup repository
         run: |
           echo "Pulling changes from backup repository"
-          git pull backup main --rebase || echo "No changes to pull"
+          git pull backup main --rebase || echo "No changes to pull" || { echo "Pull failed"; exit 1; }
 
       - name: Push to backup repository
         run: |
           echo "Pushing to remote repository"
-          git push backup ${{ env.BRANCH_NAME }} --force
+          git push backup ${{ env.BRANCH_NAME }} --force || { echo "Push failed"; exit 1; }
