Update backup.yml

diff --git a/.github/workflows/backup.yml b/.github/workflows/backup.yml
--- a/.github/workflows/backup.yml
+++ b/.github/workflows/backup.yml
@@ -9,32 +9,41 @@ jobs:
   backup:
     runs-on: ubuntu-latest
 
-    defaults:
-      run:
-        shell: bash
-
     steps:
-      - name: Use Node.js 20
-        uses: actions/setup-node@v3
+      - name: Checkout repository
+        uses: actions/checkout@v4
         with:
-          node-version: '20'
-
-      - name: Checkout source repository
-        uses: actions/checkout@v2
+          fetch-depth: 0 # Fetch all branches
 
       - name: Set up Git
         run: |
+          echo "Setting up Git configuration"
           git config --global user.name 'github-actions'
           git config --global user.email 'github-actions@github.com'
 
       - name: Create backup branch
+        id: create_branch
         run: |
+          echo "Creating backup branch"
           TIMESTAMP=$(date +"%Y%m%d%H%M%S")
           BRANCH_NAME="backup-$TIMESTAMP"
-          git checkout -b $BRANCH_NAME
-          git add .
-          git commit -m "Backup on $TIMESTAMP"
-          git remote add backup https://github.com/kn-oz/BACKUPREPO.git
-          git push -u backup $BRANCH_NAME
-        env:
-          PAT: ${{ secrets.PAT }}
+          echo "Branch name: $BRANCH_NAME"
+          git checkout -b $BRANCH_NAME || { echo "Branch creation failed"; exit 1; }
+          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
+
+      - name: Add backup remote
+        run: |
+          echo "Adding remote backup repository"
+          git remote add backup https://${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}@github.com/kn-oz/BACKUPREPO.git || { echo "Adding remote failed"; exit 1; }
+          git remote -v # List remotes to verify
+
+      - name: Pull changes from backup repository
+        run: |
+          echo "Pulling changes from backup repository"
+          git pull backup main --rebase || echo "No changes to pull" || { echo "Pull failed"; exit 1; }
+
+      - name: Push to backup repository
+        run: |
+          echo "Pushing to remote repository"
+          git push backup ${{ env.BRANCH_NAME }} --force || { echo "Push failed"; exit 1; }
+
